#! /bin/bash

CURRDIR=`pwd`

echo "File: contents, autogenerated";
echo "Purpose: list out what is in this directory";
echo " ";

for dir in `ls $CURRDIR`; do
    echo "";
    echo "$dir";
	if [ -d $dir ]; then
		echo "contents of this directory:";
		for d in `ls $dir`; do
		    echo "$d"
		done
		echo "";
	fi
done
